/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;

/**
 *
 * @author zoebe
 */
public class VtPPA extends javax.swing.JFrame
{

    /**
     * Creates new form VtPPA
     */
    public VtPPA()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        exist = new javax.swing.JTextField();
        fechacad = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas de Productos Pereceberos");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Nombre del producto");

        jLabel2.setText("Fecha de caducidad del producto");

        jLabel3.setText("Cantidad del producto");

        jLabel4.setText("Precio del producto");

        nom.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nomKeyTyped(evt);
            }
        });

        precio.setEnabled(false);
        precio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                precioActionPerformed(evt);
            }
        });
        precio.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                precioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                precioKeyTyped(evt);
            }
        });

        exist.setEnabled(false);
        exist.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                existActionPerformed(evt);
            }
        });
        exist.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                existKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                existKeyTyped(evt);
            }
        });

        fechacad.setEnabled(false);
        fechacad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fechacadActionPerformed(evt);
            }
        });
        fechacad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                fechacadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                fechacadKeyTyped(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                aceptarKeyPressed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        cancelar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(87, 87, 87)
                                .addComponent(exist))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(fechacad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(aceptar)
                        .addGap(133, 133, 133)
                        .addComponent(cancelar)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(exist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void precioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_precioActionPerformed
    {//GEN-HEADEREND:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void existActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_existActionPerformed
    {//GEN-HEADEREND:event_existActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existActionPerformed

    private void fechacadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fechacadActionPerformed
    {//GEN-HEADEREND:event_fechacadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechacadActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        try
        {
            Perecederos prcd = new Perecederos(fechacad.getText(), nom.getText(),Double.parseDouble(precio.getText()), Integer.parseInt(exist.getText()));
            VtPr.p=Manipulacion.inserta(VtPr.p,prcd);
            Mensajes.exito(this, "Registro exitoso");
            CtrlInterfaz.limpia(nom,precio,exist,fechacad);
            CtrlInterfaz.habilita(false, precio,exist,fechacad,aceptar);
            CtrlInterfaz.cambia(nom);
        } catch (Exception e)
        {
            Mensajes.error(this, "Error..."+e.toString());
        }
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void nomKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyTyped
    {//GEN-HEADEREND:event_nomKeyTyped
        Validaciones.validaAlfabeticos(evt, 15, nom.getText());
    }//GEN-LAST:event_nomKeyTyped

    private void precioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_precioKeyTyped
    {//GEN-HEADEREND:event_precioKeyTyped
        Validaciones.validaFlotantes(evt, 7, precio.getText());
    }//GEN-LAST:event_precioKeyTyped

    private void existKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_existKeyTyped
    {//GEN-HEADEREND:event_existKeyTyped
        Validaciones.validaEntero(evt, 5, exist.getText());
    }//GEN-LAST:event_existKeyTyped

    private void fechacadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechacadKeyTyped
    {//GEN-HEADEREND:event_fechacadKeyTyped
        Validaciones.validaAlfanumerico(evt,10, fechacad.getText());
    }//GEN-LAST:event_fechacadKeyTyped

    private void nomKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomKeyPressed
    {//GEN-HEADEREND:event_nomKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nom,precio);
        
    }//GEN-LAST:event_nomKeyPressed

    private void precioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_precioKeyPressed
    {//GEN-HEADEREND:event_precioKeyPressed
        
        Validaciones.enterFlotante(this, evt, precio, exist);
    }//GEN-LAST:event_precioKeyPressed

    private void existKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_existKeyPressed
    {//GEN-HEADEREND:event_existKeyPressed
        Validaciones.enterEntero(this, evt, exist, fechacad);
    }//GEN-LAST:event_existKeyPressed

    private void fechacadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechacadKeyPressed
    {//GEN-HEADEREND:event_fechacadKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, fechacad, aceptar);
    }//GEN-LAST:event_fechacadKeyPressed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_aceptarKeyPressed
    {//GEN-HEADEREND:event_aceptarKeyPressed
        if (evt.getKeyChar()=='\n')
        {
            aceptarActionPerformed(null);
        }
    }//GEN-LAST:event_aceptarKeyPressed

    private void cancelarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cancelarKeyPressed
    {//GEN-HEADEREND:event_cancelarKeyPressed
       
    }//GEN-LAST:event_cancelarKeyPressed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(nom,precio,exist,fechacad);
        CtrlInterfaz.habilita(false, precio,exist,fechacad,aceptar);
        CtrlInterfaz.cambia(nom);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtPPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtPPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtPPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtPPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtPPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField exist;
    private javax.swing.JTextField fechacad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables
}
